project:
  type: website
  output-dir: docs

website:
  title: "Gadha Krishna Leons"
  site-url: "https://gadhak.github.io/gadha_portfolio/"
  
  navbar:
    background: "#453c5c"  # Muted Dark Purple
    foreground: "#ffffff"  # White text
    right:
      - text: Home
        href: index.qmd
      - text: Research & Skills
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Beyond Science
        href: extracurricular.qmd
      - text: CV
        href: cv.pdf
        
      # Icons removed. The Dark Mode toggle appears automatically here.

format:
  html:
    theme: 
      light: cosmo  # The standard look
      dark: slate   # The dark mode look
    css: styles.css
    mainfont: "Nunito Sans"
    monofont: "Fira Code"
    toc: false
    